mozilla-releng/beetmoverscript

- beetmoverscript/constants.py
@lundjordan 
1. Few errors made the (usigned artifacts) BM build to fail. At a second look in the logs, it failed with the following error:
2016-11-04T16:57:44     INFO -   File "/builds/beetmoverworker/lib/python3.5/site-packages/botocore/validate.py", line 270, in serialize_to_request
2016-11-04T16:57:44     INFO -     raise ParamValidationError(report=report.generate_report())
2016-11-04T16:57:44     INFO - botocore.exceptions.ParamValidationError: Parameter validation failed:
2016-11-04T16:57:44     INFO - Invalid type for parameter ContentType, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
2016-11-04T16:57:45     INFO - exit code: 1
2. All files were correctly copied to S3 but oddly these three JSON files:
json:
artifact: {{ locale_prefix }}target.json
s3_key: {{ …
> Bug 1313154 - enrich mimetypes with json extension too. r=jlund

- beetmoverscript/script.py
- beetmoverscript/templates/fennec_nightly_en_us_multi_signed.yml
- beetmoverscript/templates/fennec_nightly_en_us_multi_unsigned.yml
- beetmoverscript/templates/firefox_nightly_en_us_signed.yml
- beetmoverscript/templates/firefox_nightly_en_us_unsigned.yml
@lundjordan r?
Obs:
1. For "tc_fennec_nightly" => "tc_nightly" change, I'll adapt accordingly https://github.com/mozilla-releng/balrogscript/blob/master/bin/balrogworker.py#L179 as soon as this lands.
2. I re-double-checked the files under our staging bucket against http://archive.mozilla.org/pub/mobile/nightly/latest-mozilla-central-android-api-15/ and made the corrections.
3. The same for desktop nightlies from our staging bucket against http://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/ and made the corrections.
4. Tweaked the checksums accordinly in both Fennec/Firefox, since we now have them on the signing tasks side.
5. Changed to CMAR from tar.bz2 for the file to be sent to Balrog.
6. I left few TODOs in the code for later on, reminders for us to add those …
> Bug 1313154 - adapt beetmoverscript to cope with desktop nightlies.

- beetmoverscript/test/fake_config.json
- config_example.json
This is good for new installs; we'll also need a puppet patch for prod installs.
> bug 1333895 - reduce max concurrent connections

- beetmoverscript/script.py
When we upload many artifacts in parallel, we often see many log lines with a status line but no sign of which artifact was uploaded.  By adding the path to the log, we'll be able to trace this easier.
> add path to upload log status

- beetmoverscript/constants.py
Changed application/zip to application/x-xpinstall for direct install of langpacks in archive.mozilla.org
Referring to bugzilla (Bug 1336754) -
https://bugzilla.mozilla.org/show_bug.cgi?id=1336754
> Bug 1336754 (Bugzilla) - Changed application/zip to application/x-xpinstall

- beetmoverscript/constants.py
- beetmoverscript/test/test_utils.py
- beetmoverscript/utils.py
@escapewindow @JohanLorenzo 
Latest jamun-based staging Fennec beetmover tasks fail because of `jinja2.exceptions.UndefinedError: 'build_number' is undefined`. More logs can be found here[1].
That is because initially we chained the `version` and `build_number` to the bucket scope, instead of the action scope. So far we could have only extracted and enriched the context with `version` and `build_number` if the release scopes were present. This failed on `jamun` as we're using `dep` bucket scopes and `push-to-candidates` action scopes. 
This PR is changing this behavior so that it's no longer chained to bucket scopes but instead to action scopes, so that any release scheduled on try, or jamun or any other low-level branch can actually be generated as long as a `build_number` and `version` …
> Bug 1343649 - fix build_number and version within various action types. r=jlorenzo

- beetmoverscript/constants.py
- beetmoverscript/templates/fennecaarch64_candidates.yml
- beetmoverscript/templates/fennecaarch64_nightly.yml
Add templates for uploading the new Fennec AArch64 Nightly. The templates are copied from the corresponding x86 templates, with the architecture name replaced.
I think that's all that's needed, but I'm not sure how to actually test that.
> Bug 1366404 - Add templates for AArch64

- beetmoverscript/script.py
- version.json
We're currently dying on uncaught exceptions in `retry_async`: https://bugzilla.mozilla.org/show_bug.cgi?id=1364765
I would have limited this to only aiohttp exceptions, but the one highlighted in that bug is a `
concurrent.futures._base.CancelledError`.  `Exception` is a catch-all.
@MihaiTabara , @lundjordan can one of you take a look?
> bug 1364765 - retry on any exception.

- beetmoverscript/templates/firefox_nightly.yml
Follow up #73. It turns out every locale but en-US is uploaded. This patch fixes it.
> Bug 1381508 - part 2: Upload win en-US installers to l10n dirs

- beetmoverscript/script.py
- beetmoverscript/templates/firefox_nightly.yml
- beetmoverscript/templates/firefox_nightly_repacks.yml
- beetmoverscript/test/fake_beetmover_manifest.yml
- beetmoverscript/test/test_script.py
The outbound manifest, used by balrog scriptworker, needs to
have information about partials added.
It's unwise to add a partial if there's no related complete,
so this involves a refactor so that instead of directly
populating context.balrog_manifest, we instead fill a
staging area with details about the files we have uploaded.
Once all uploads are done, we generate the balrog manifest
to be of the expected form.
[
{
"tc_nightly": true,
"extVersion": "",
"appVersion": "",
"completeInfo": [
{
"hash": "...",
"url": "...",
"size": 
}
],
"partialInfo": [
{
"hash": "...",
"url": "...",
"size": 
}
],
"platform": "",
"buildid": "",
"locale": "",
"branch": "",
"url_replacements": [],
"hashType": "sha512",
"appName": "Firefox"
}
]
> Bug 1396797 Support for partials in manifest

- .gitignore
- beetmoverscript/test/test_script.py
When I ran tox locally, `test_move_beets` failed because `completeInfo` isn't sorted... the async call puts the `completeInfo` in in random order.
This PR sorts `completeInfo` before the assertion test. It also adds `test_artifact_dir` to `.gitignore`, since we create some random artifacts. At some point we may want to create a tmpdir that's automatically cleaned up after each test.
> Test improvements

- CHANGELOG.md
- beetmoverscript/constants.py
- beetmoverscript/task.py
- beetmoverscript/test/test_task.py
- beetmoverscript/test/test_utils.py
- beetmoverscript/utils.py
- version.json
I debated lumping push-to-candidates with push-to-releases, and it looks
like the schema change busted push-to-candidates. This patch separates
them back out.
> fix fennec beetmover candidates

- CHANGELOG.md
- beetmoverscript/templates/firefox_nightly.yml
- beetmoverscript/templates/firefox_nightly_repacks.yml
- version.json
We've reached a resolution under [bug 1405622](https://bugzilla.mozilla.org/show_bug.cgi?id=1405622) to:
- stop publishing partial mars under latest directories for both `en-US` and `locales`
- have a dedicated subdir for these instead to ease the implementation of a lifecycle policy 
- locale partial.mar are going in the `date-branch-l10n` subdirs as opposed to `date-branch` where `en-US` lives
> Bug 1405622 - Stop publishing PMARs under latest dirs and assign dedicated subdir.

- beetmoverscript/constants.py
If https://bugzilla.mozilla.org/show_bug.cgi?id=1336514#c33 gets r+ this can be "uplifted"
> Bug 1336514 - Publish jsshell-*.zip

- .gitignore
pytest 3.4.0 comes with a new folder. Let's ignore it from git. pytest did the same in https://github.com/pytest-dev/pytest/commit/ab00c3e9117e22f4a7e138cbbb5b6c8754bf3102
> Add .pytest_cache directory to gitignore

- CHANGELOG.rst
- beetmoverscript/constants.py
- beetmoverscript/newsfragments/1473259.added
- beetmoverscript/templates/firefox_nightly.yml
These changes are similar to what catlee did before for Linux to support asan-reporter.
I am currently working on Windows support in bug 1473259 but Mac support is also planned and I figured it is easier to make these changes in one on the beetmover side, so it is less work to deploy.
I am also going to change the m-c patch in that bug to match the platform descriptor used here (win64-asan-reporter).
> Support win64-asan-reporter and mac-asan-reporter platforms

- beetmoverscript/templates/maven_geckoview.yml
- beetmoverscript/test/test_utils.py
Tested with https://maven-default.stage.mozaws.net/maven2/org/mozilla/geckoview/geckoview-nightly-try-x86/63.0.20180827145613/geckoview-nightly-try-x86-63.0.20180827145613.aar coming from graph 
https://treeherder.mozilla.org/#/jobs?repo=try&revision=5a4ded81f879b843e06a30e52c4598c21115f9f8&selectedJob=196109867
> Bug 1484932 - Update GeckoView maven group id: org.mozilla.geckoview

- beetmoverscript/constants.py
- beetmoverscript/script.py
- beetmoverscript/test/test_script.py
This also adds an explicit test if there is no detected Mime Type to make future discovery of this issue easier.
> Support msi mime type

- beetmoverscript/newsfragments/1493942.fixed
- beetmoverscript/zip.py
For some reason during development I assumed that all maven tasks were coming from the mobile world, hence they had the rendering template in the good old fashioned way. I totally missed that declarative artifacts changed the way we organize artifacts within in-tree as well, where on central for nightlies we have the `geckoview`. I tested this locally and this should unblock us for now. After we migrate everything to declarative artifacts, beetmoverscript tests are going to be rewritten so that we have integration tests for all possible scenarios.
CC @srfraser @lundjordan Another reason for wh we need declarative artifacts rolled-out to all products / channels 😳
> Fix geckoview tasks after snapshots enabled.

- beetmoverscript/script.py
- beetmoverscript/task.py
- beetmoverscript/test/test_utils.py
- beetmoverscript/test/test_work_dir/cot/eSzfNqMZT_mSiQQXu8hyqg/public/build/buildhub.json
- beetmoverscript/utils.py
In order to translate the full local scriptworker path into an artifact, we
were using `os.path.basename` and then searching through the artifact map,
ignoring locales. This caused the first match to be returned, whether or not it
was correct.
This new variant passes in both the full local path and the upstream artifact
path, so we can match against the full artifact path instead, removing a chance
of duplicate matches.
> Bug 1542500 Finding the right upstream artifact
